---
- name: "Restart named"
  ansible.builtin.service:
    name: "{{ dns_bind_service }}"
    state: restarted

- name: "Reload named"
  ansible.builtin.service:
    name: "{{ dns_bind_service }}"
    state: reloaded
