---
dns_bind_packages:
  - bind
  - bind-utils

dns_bind_service: "named"
dns_bind_conf_dir: "/etc"
dns_bind_zones_dir: "/var/named"
dns_bind_conf_file: "/etc/named.conf"

dns_bind_domain: "jmelol.lab"
dns_bind_server_ip: "192.168.100.10"
dns_bind_server_hostname: "ns1"
dns_bind_zone_serial: "2025062401"

dns_bind_ttl: 86400
dns_bind_refresh: 3600
dns_bind_retry: 900
dns_bind_expire: 604800
dns_bind_minimum_ttl: 3600

dns_bind_allow_query: "any"
dns_bind_recursion: "yes"
dns_bind_listen_on: "127.0.0.1; 192.168.100.10"
dns_bind_listen_on_v6: "none"

dns_bind_forwarders:
  - "8.8.8.8"
  - "8.8.4.4"

dns_bind_reverse_zone_name: "100.168.192.in-addr.arpa"
dns_bind_a_records:
  - { name: "ns1", ip: "192.168.100.10", ptr: "10" }
