---
# ================================================================
#  roles/dhcpd/handlers/main.yml
# ================================================================

- name: "Restart dhcpd"
  ansible.builtin.service:
    name: "{{ dhcpd_service }}"
    state: restarted
- name: "Reload systemd"
  ansible.builtin.systemd:
    daemon_reload: true
