---
# ================================================================
#  roles/dhcpd/handlers/main.yml
# ================================================================

- name: "restart dhcpd"
  ansible.builtin.service:
    name: "{{ dhcp_service }}"
    state: restarted
