---
# ================================================================
#  roles/dhcpd/defaults/main.yml
# ================================================================

dhcpd_package: "dhcp-server"
dhcpd_service: "dhcpd"
dhcpd_conf_file: "/etc/dhcp/dhcpd.conf"

# Corregido: Solo un espacio despu√©s de los dos puntos
dhcpd_domain_name: "example.lab"
dhcpd_domain_name_servers: ["192.168.1.10"]

dhcpd_default_lease_time: 3600
dhcpd_max_lease_time: 86400

# Interfaz de escucha
dhcpd_interface: "eth1"

dhcpd_subnets: []
dhcpd_reservations: []
